version: '3.8'

services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:14-alpine
    container_name: contracting_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: contracting_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      # Expose port 5432 to the host for direct database access if needed
      - "5432:5432"
    restart: unless-stopped

  # Authentication Backend Service
  auth:
    container_name: contracting_auth
    build:
      context: ./backend
      dockerfile: services/auth/Dockerfile
    ports:
      # Expose port 8001 on the host to be accessible by the frontend client
      - "8001:80"
    # Load sensitive variables from a .env file at the project root
    env_file:
      - .env
    environment:
      # Non-sensitive variables can remain here
      - DATABASE_URL=postgresql://user:pass@postgres:5432/contracting_db
      - ACTIVITY_SERVICE_URL=http://activity:80/activities/
    depends_on:
      - postgres
    restart: unless-stopped

  # Projects Backend Service
  projects:
    container_name: contracting_projects
    build:
      context: ./backend
      dockerfile: services/projects/Dockerfile
    ports:
      - "8002:80"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/contracting_db
      - ACTIVITY_SERVICE_URL=http://activity:80/activities/
    depends_on:
      - postgres
    restart: unless-stopped

  # Accounting Backend Service
  accounting:
    container_name: contracting_accounting
    build:
      context: ./backend
      dockerfile: services/accounting/Dockerfile
    ports:
      - "8003:80"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/contracting_db
      - ACTIVITY_SERVICE_URL=http://activity:80/activities/
    depends_on:
      - postgres
    restart: unless-stopped

  # HR Backend Service
  hr:
    container_name: contracting_hr
    build:
      context: ./backend
      dockerfile: services/hr/Dockerfile
    ports:
      - "8004:80"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/contracting_db
      - ACTIVITY_SERVICE_URL=http://activity:80/activities/
    depends_on:
      - postgres
    restart: unless-stopped

  # Tasks Backend Service
  tasks:
    container_name: contracting_tasks
    build:
      context: ./backend
      dockerfile: services/tasks/Dockerfile
    ports:
      - "8005:80"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/contracting_db
      - ACTIVITY_SERVICE_URL=http://activity:80/activities/
    depends_on:
      - postgres
    restart: unless-stopped

  # Quotes Backend Service
  quotes:
    container_name: contracting_quotes
    build:
      context: ./backend
      dockerfile: services/quotes/Dockerfile
    ports:
      - "8006:80"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/contracting_db
      - ACTIVITY_SERVICE_URL=http://activity:80/activities/
    depends_on:
      - postgres
    restart: unless-stopped

  # Analytics Backend Service
  analytics:
    container_name: contracting_analytics
    build:
      context: ./backend
      dockerfile: services/analytics/Dockerfile
    ports:
      - "8007:80"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/contracting_db
    depends_on:
      - postgres
    restart: unless-stopped

  # Activity Backend Service
  activity:
    container_name: contracting_activity
    build:
      context: ./backend
      dockerfile: services/activity/Dockerfile
    ports:
      - "8008:80"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/contracting_db
    depends_on:
      - postgres
    restart: unless-stopped

  # CV Backend Service
  cv:
    container_name: contracting_cv
    build:
      context: ./backend
      dockerfile: services/cv/Dockerfile
    ports:
      - "8009:80"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/contracting_db
    depends_on:
      - postgres
    restart: unless-stopped

  # Frontend Web Application Service
  frontend:
    container_name: contracting_frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      # These URLs are used by the client-side browser to reach the backend services
      - NEXT_PUBLIC_API_URL=http://localhost:8001
      - NEXT_PUBLIC_PROJECTS_API_URL=http://localhost:8002
      - NEXT_PUBLIC_ACCOUNTING_API_URL=http://localhost:8003
      - NEXT_PUBLIC_HR_API_URL=http://localhost:8004
      - NEXT_PUBLIC_TASKS_API_URL=http://localhost:8005
      - NEXT_PUBLIC_QUOTES_API_URL=http://localhost:8006
      - NEXT_PUBLIC_ANALYTICS_API_URL=http://localhost:8007
      - NEXT_PUBLIC_ACTIVITY_API_URL=http://localhost:8008
      - NEXT_PUBLIC_CV_API_URL=http://localhost:8009
    depends_on:
      - auth
      - projects
      - accounting
      - hr
      - tasks
      - quotes
      - analytics
      - activity
      - cv
    restart: unless-stopped

# Define the named volume for persisting database data
volumes:
  postgres_data:
